{{- if (eq .Values.deployment "daemonset") -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "logstream-workergroup.fullname" . }}
  labels:
    {{- include "logstream-workergroup.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "logstream-workergroup.selectorLabels" . | nindent 6 }}
  {{- if (.Values.strategy) }}
  {{- if and (ne .Values.strategy.type "Recreate") (ne .Values.strategy.type "RollingUpdate") }}
      {{- fail (printf "Not a valid strategy type for DaemonSet (%s)" .Values.strategy.type) }}
  {{- end }}
  updateStrategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "logstream-workergroup.selectorLabels" . | nindent 8 }}

    spec:
      {{- include "workergroup.pod" . | nindent 8 }}
{{- end }}