apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "appscope.fullname" . }}-cluster-role-binding
  labels:
  {{- include "appscope.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "appscope.fullname" . }}-cluster-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "appscope.fullname" . }}-cert-sa'
  namespace: '{{ .Release.Namespace }}'
