{{- if or .Values.podSecurityContext .Values.securityContext }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstream-leader.fullname" . }}-gitconfig
  labels:
    {{- include "logstream-leader.labels" . | nindent 4 }}
data:
  .gitconfig: |
    [safe]
    directory = {{ .Values.config.criblHome }}/config-volume
{{- end }}