{{- if (eq .Values.deployment "daemonset") -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "logstream-workergroup.fullname" . }}
  labels:
    {{- include "logstream-workergroup.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "logstream-workergroup.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "logstream-workergroup.selectorLabels" . | nindent 8 }}

    spec:
      {{- include "workergroup.pod" . | nindent 8 }}
{{- end }}