{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "logstream-aws.fullname" . }}
  labels:
    {{- include "logstream-aws.labels" . | nindent 4 }}
{{- end }}
